
-- BUDGETING: Intermediate & Advanced
INSERT INTO financial_lessons (title, category, difficulty, content, duration_minutes, order_index) VALUES
('Zero-Based Budgeting Mastery', 'budgeting', 'intermediate', E'Zero-based budgeting (ZBB) assigns every shilling a job — income minus all allocations must equal zero.\n\n## How It Works\n1. **Start with total monthly income** (salary, side hustles, investments)\n2. **List every expense category** — needs, wants, savings, debt payments\n3. **Allocate until you hit zero** — leftover goes to savings or debt\n\n## Why It''s Powerful\n- Eliminates "where did my money go?" syndrome\n- Forces intentional spending decisions\n- Reveals hidden spending leaks immediately\n\n## Pro Strategy: Rolling ZBB\nReview your zero-based budget weekly. If you underspent groceries by 15,000 TZS, reallocate to savings goals mid-month. This dynamic approach can boost your savings rate by 8-15%.\n\n## Advanced Tip\nCreate "buffer categories" for irregular expenses (car repairs, medical). Allocate 5-10% of income here. When unused, roll into an opportunity fund for investments.', 8, 10),

('Envelope System for Digital Money', 'budgeting', 'intermediate', E'The envelope system works brilliantly with mobile money and digital banking.\n\n## Digital Envelope Strategy\n1. **Create separate M-Pesa/bank sub-accounts** for each spending category\n2. **On payday, distribute funds** to each "envelope" account\n3. **Spend only from the designated envelope** — when empty, stop\n\n## Category Envelopes\n- Housing & Utilities: 30% of income\n- Food & Groceries: 15%\n- Transport: 10%\n- Health: 5%\n- Entertainment: 5%\n- Education: 5%\n- Savings: 20%\n- Miscellaneous: 10%\n\n## Pro Tips\n- Use FinFlow accounts to simulate envelopes digitally\n- Review and adjust percentages quarterly based on actual spending\n- "Envelope stuffing" on payday creates psychological spending barriers\n- Track which envelopes consistently overflow or run dry', 7, 11),

('Behavioral Budgeting: Psychology of Spending', 'budgeting', 'advanced', E'Understanding WHY you spend is more powerful than tracking WHAT you spend.\n\n## The 4 Spending Personalities\n1. **The Comfort Spender** — buys to feel safe\n2. **The Status Spender** — buys to impress\n3. **The Emotional Spender** — buys to cope\n4. **The Avoidant Spender** — ignores finances entirely\n\n## Cognitive Biases That Drain Your Wallet\n- **Anchoring**: A 500,000 TZS item "on sale" for 350,000 feels cheap\n- **Mental Accounting**: Treating a bonus differently from salary\n- **Present Bias**: Valuing 50,000 TZS today over 200,000 TZS in 2 years\n- **Social Proof**: "Everyone else has it"\n\n## Rewiring Your Brain\n1. **24-Hour Rule**: Wait 24 hours before any purchase over 50,000 TZS\n2. **Cost-Per-Use**: 200,000 TZS jacket worn 100 times = 2,000/wear (great)\n3. **Opportunity Cost Thinking**: "This dinner = 3 months of T-bill interest"\n4. **Values Alignment Audit**: Does your spending match your top 5 values?', 10, 12);

-- SAVINGS: Intermediate & Advanced
INSERT INTO financial_lessons (title, category, difficulty, content, duration_minutes, order_index) VALUES
('The Savings Waterfall Strategy', 'savings', 'intermediate', E'Build a layered savings system that protects and grows your wealth.\n\n## The 4-Tier Savings Waterfall\n\n### Tier 1: Emergency Buffer (1 month expenses)\nKeep in M-Pesa or instant-access savings. Target: 500,000 - 1,000,000 TZS\n\n### Tier 2: Emergency Fund (3-6 months expenses)\nKeep in high-yield savings account. Target: 3,000,000 - 9,000,000 TZS\n\n### Tier 3: Opportunity Fund (10-20% of annual income)\nKeep in short-term T-bills or money market. Accessible within 30-90 days.\n\n### Tier 4: Wealth Building (everything above)\nDeploy into long-term investments. 5+ year time horizon.\n\n## Pro Strategy\nAutomate transfers on payday: Salary splits across all 4 tiers automatically. What you don''t see, you don''t spend.', 8, 13),

('Compound Interest: The 8th Wonder', 'savings', 'advanced', E'Compound interest is the most powerful force in wealth building.\n\n## The Math That Changes Everything\n- Simple Interest: 1,000,000 TZS at 10% for 20 years = 3,000,000 TZS\n- Compound Interest: 1,000,000 TZS at 10% for 20 years = 6,727,500 TZS\n\n## The Rule of 72\nDivide 72 by your interest rate to find doubling time:\n- At 8%: 9 years to double\n- At 12%: 6 years to double\n- At 15%: 4.8 years to double\n\n## Real East African Returns (2024-2026)\n- Tanzania T-Bills (91-day): ~5-8% annually\n- Tanzania T-Bills (364-day): ~8-11% annually\n- Kenya M-Akiba Bonds: ~10-12%\n- SACCO Deposits: ~8-15%\n\n## The Cost of Waiting\nStarting 5 years late with the same monthly contribution can cost you 30-40% of your final wealth. Every month you delay is permanently lost compounding time.\n\n## Action Steps\n1. Calculate your wealth doubling timeline using Rule of 72\n2. Set up automatic monthly contributions\n3. Reinvest ALL returns — never withdraw interest\n4. Increase contributions by at least inflation rate annually', 10, 14),

('Savings Automation & Round-Up Strategies', 'savings', 'intermediate', E'The best savings plan is one you never have to think about.\n\n## Automation Framework\n\n### Pay Yourself First\nPayday → 20% immediately to savings. NOT: Payday → bills → spend → save leftovers.\n\n### Round-Up Savings\nEvery transaction, round up to the nearest 1,000 or 5,000 TZS. Over 30 daily transactions: 30,000-90,000 TZS/month saved painlessly.\n\n### The 1% Escalation\nIncrease savings rate by 1% every month. Month 1: 10%, Month 12: 21%. You barely notice but the effect is massive.\n\n### Windfall Rules\nAny unexpected money: 50% savings, 30% debt payoff, 20% guilt-free spending.\n\n## Psychology Hack\nName your savings goals emotionally: "Freedom Fund" not "Savings Account." Emotional names increase contribution rates by 30%.', 7, 15);

-- INVESTING: Full spectrum
INSERT INTO financial_lessons (title, category, difficulty, content, duration_minutes, order_index) VALUES
('Investment Fundamentals: Risk & Return', 'investing', 'beginner', E'Every investment decision is a tradeoff between risk and return.\n\n## The Risk-Return Spectrum\n\n### Low Risk, Low Return\n- Savings accounts (2-5%), Government T-bills (5-11%), Fixed deposits (6-10%)\n\n### Medium Risk, Medium Return\n- Corporate bonds (8-15%), SACCO investments (8-15%), Unit trust funds (8-18%), Real estate (10-20%)\n\n### High Risk, High Return\n- Individual stocks (variable), Cryptocurrency (extremely variable), Startup investments, Forex trading\n\n## Key Concepts\n- **Diversification**: Don''t put all eggs in one basket\n- **Correlation**: Choose assets that don''t all move together\n- **Liquidity**: Can you access your money quickly?\n- **Time Horizon**: Longer = more risk tolerance\n\n## Your First Investment\nBegin with government T-bills. Virtually risk-free, pay better than savings accounts, and teach you the discipline of locking money away.', 8, 20),

('Treasury Bills & Bonds: Risk-Free Returns', 'investing', 'intermediate', E'Government securities are the foundation of any serious investment portfolio in East Africa.\n\n## Tanzania Treasury Bills\n1. Government borrows money from you\n2. You buy at a discount (e.g., pay 950,000 for 1,000,000 face value)\n3. At maturity, receive full face value. The difference is your return.\n\n### Types\n- 91-day T-bill: ~5-8% annualized\n- 182-day T-bill: ~7-10% annualized\n- 364-day T-bill: ~8-11% annualized\n\n## Treasury Bonds\n- Longer term: 2, 5, 7, 10, 15, 25 years\n- Higher returns: 10-16% depending on tenor\n- Semi-annual coupon payments\n- Tradeable on secondary market\n\n## Strategy: T-Bill Ladder\nBuy T-bills with staggered maturities so one matures every month — regular income with full investment.\n\n## Tax Advantage\nGovernment securities in Tanzania are exempt from withholding tax on interest.', 10, 21),

('Stock Market Investing for East Africans', 'investing', 'intermediate', E'The DSE and NSE offer wealth-building opportunities.\n\n## Getting Started\n1. Open a CDS Account through a licensed broker\n2. Choose a broker (Core Securities, Orbit, Zan Securities)\n\n## How to Analyze Stocks\n- **P/E Ratio**: Price / Earnings. Under 10 = potentially undervalued\n- **Dividend Yield**: Above 5% = attractive income\n- **Book Value**: Trading below = potential bargain\n- **Revenue Growth**: Year over year trend\n\n## Portfolio Strategy\n- Core holdings (60%): Blue-chip, dividend-paying stocks\n- Growth (30%): Smaller companies with expansion potential\n- Speculative (10%): Higher risk, higher reward\n\n## Common Mistakes\n- Buying on tips without research\n- Panic selling during dips\n- Over-concentrating in one sector\n- Ignoring dividends (they compound!)', 12, 22),

('Unit Trusts & Collective Investment Schemes', 'investing', 'intermediate', E'Unit trusts pool money from many investors for professional management.\n\n## Types of Funds\n- **Money Market Funds**: T-bills, deposits. Low risk, 6-10% return\n- **Balanced Funds**: Mix of stocks and bonds. Medium risk, 8-15%\n- **Equity Funds**: Primarily stocks. Higher risk, 10-25%\n\n## Key Providers\nUTI, CBA Unit Trust, British American, Old Mutual\n\n## Advantages Over Direct Stock Picking\n- Professional management\n- Instant diversification\n- Lower minimum (often 50,000-100,000 TZS)\n- Regulated by CMSA\n\n## Fees to Watch\n- Management fee: 1-3% annually\n- Entry/exit fees: 0-2%\n- Compare net-of-fees returns, not gross', 10, 23),

('Real Estate Investment Strategies', 'investing', 'advanced', E'Real estate is the traditional wealth builder in East Africa.\n\n## Investment Approaches\n1. **Rental Properties**: 5-10% residential yield, 8-15% commercial\n2. **Land Banking**: Buy in growth corridors, hold 3-10 years\n3. **Investment Groups**: Pool capital with partners (get legal agreements!)\n4. **REITs**: Trade like stocks, growing in Kenya\n\n## Financial Analysis\n- **Cap Rate**: Net Operating Income / Property Value (aim 8%+)\n- **Cash-on-Cash Return**: Annual cash flow / Total cash invested\n- **Gross Rent Multiplier**: Price / Annual rent (lower = better)\n\n## Due Diligence Checklist\n- Verify title deed at Ministry of Lands\n- Check for encumbrances and liens\n- Survey boundaries\n- Verify zoning and permitted use\n- Research development plans\n- Calculate ALL costs (transfer tax, legal, renovation)', 15, 24),

('Cryptocurrency & Digital Assets', 'investing', 'advanced', E'Crypto is volatile but increasingly relevant. Approach it intelligently.\n\n## Risk Management Rules\n1. Never invest more than 5-10% of portfolio in crypto\n2. Dollar-Cost Average: fixed amount monthly regardless of price\n3. Use cold storage for long-term holdings\n4. If it promises guaranteed returns, it''s a scam\n\n## Smart Strategies\n- Stack sats: Buy small amounts of Bitcoin regularly\n- Stablecoin savings: Earn 3-8% APY on USD stablecoins\n- Learn DeFi gradually with established protocols only\n\n## Red Flags\n- "Guaranteed 2% daily returns"\n- Pressure to recruit others\n- Unverifiable team\n- Celebrity endorsement schemes', 10, 25),

('Portfolio Construction & Asset Allocation', 'investing', 'advanced', E'Professional portfolio management is about allocation, not picking winners.\n\n## Allocation Frameworks\n\n### Conservative\n50% Government securities, 25% Money market, 15% Blue-chips, 10% Real estate\n\n### Balanced\n30% Gov securities, 20% Corporate bonds, 25% Stocks, 15% Real estate, 10% Alternative\n\n### Aggressive\n10% Gov securities, 15% Bonds, 40% Stocks, 15% Real estate, 15% Alternative, 5% Speculative\n\n## Rebalancing\nEvery 6 months, review allocation. If stocks grew beyond target, sell some and buy bonds. This forces "buy low, sell high" systematically.\n\n## Age-Based Rule\n% in bonds = Your age. A 30-year-old: 30% bonds, 70% growth.\n\n## Diversify Across\n- Asset classes, Geographies, Sectors, Time horizons', 12, 26);

-- DEBT: New category
INSERT INTO financial_lessons (title, category, difficulty, content, duration_minutes, order_index) VALUES
('Understanding Good Debt vs Bad Debt', 'debt', 'beginner', E'Not all debt is created equal.\n\n## Good Debt (Leverages Your Future)\n- Education loans: Increase earning potential\n- Business loans: Generate income exceeding interest\n- Mortgage: Building equity in appreciating asset\n\n## Bad Debt (Drains Your Future)\n- Credit card balances at 2-4% monthly\n- Consumer loans for lifestyle\n- Payday/emergency loans at 10-30% monthly\n- Borrowing from multiple mobile lenders\n\n## The Debt Test\n1. Will this generate more income than it costs?\n2. Will the asset appreciate or depreciate?\n3. Can I afford payments from existing cash flow?\n4. What''s the total cost including ALL interest?\n\n## Mobile Lending Trap\nApps like Tala, Branch charge 7-15% monthly. A 100,000 TZS loan at 10% monthly = 120%+ annualized interest.', 6, 30),

('Debt Avalanche vs Snowball Strategy', 'debt', 'intermediate', E'Two proven strategies to become debt-free.\n\n## Debt Avalanche (Mathematically Optimal)\nList debts by INTEREST RATE (highest first). Pay minimums on all, throw extra at highest rate.\nAdvantage: Saves the most money in total interest.\n\n## Debt Snowball (Psychologically Powerful)\nList debts by BALANCE (smallest first). Pay minimums on all, throw extra at smallest balance.\nAdvantage: Quick wins build momentum and motivation.\n\n## Which to Choose?\n- Disciplined and math-driven → Avalanche\n- Need emotional wins → Snowball\n- Similar rates → Snowball for psychology\n\n## The Hybrid Approach\nPay off one small debt first (quick win), then switch to avalanche. Best of both worlds.', 8, 31),

('Negotiating & Restructuring Debt', 'debt', 'advanced', E'You have more power over your debt than you think.\n\n## Bank Loan Negotiation\n- Request 1-3% rate reduction if you''re a good customer\n- Extend tenure for lower monthly payments\n- Consolidate multiple loans into one at lower rate\n- Request payment holidays during genuine hardship\n\n## SACCO Loan Advantages\n- Lower rates (12-18% vs 24-36% for banks)\n- Flexible terms, loans against savings\n- Group guarantee reduces rates\n\n## Debt Restructuring Signs\nIf 3+ apply, seek formal restructuring:\n- Debt payments exceed 40% of income\n- Using new debt to pay old debt\n- Missing payments regularly\n- Anxiety about finances', 10, 32);

-- TAX: New category
INSERT INTO financial_lessons (title, category, difficulty, content, duration_minutes, order_index) VALUES
('Tax Basics for East African Earners', 'tax', 'beginner', E'Understanding tax is understanding how to keep more of what you earn.\n\n## Tanzania Income Tax Brackets (PAYE)\n- 0 - 270,000 TZS/month: 0%\n- 270,001 - 520,000: 8%\n- 520,001 - 760,000: 20%\n- 760,001 - 1,000,000: 25%\n- Above 1,000,000: 30%\n\n## Tax-Efficient Strategies\n1. Government securities: Interest is tax-exempt\n2. Pension contributions: Tax-deductible\n3. Health insurance premiums: Check deductibility\n4. Business expenses: Properly documented = deductible\n\n## Filing Requirements\n- Employed: Employer files PAYE\n- Self-employed: File by June 30\n- TIN required for all financial activities', 8, 35),

('Tax Optimization & Legal Deductions', 'tax', 'intermediate', E'Legally minimizing your tax burden is smart financial management.\n\n## Maximizing Deductions\n### Employment: Pension contributions, NHIF, mortgage interest, professional development\n### Business: Office expenses, travel, equipment, professional services, marketing\n\n## Tax-Efficient Investments\n- Government T-bills/bonds: EXEMPT from withholding tax\n- Bank interest: 10% withholding tax\n- Dividends: 10% withholding tax\n\n## Record Keeping\nKeep ALL financial records for 5 years. Use FinFlow to auto-categorize and generate reports for tax filing.', 10, 36),

('Business Taxation & Structure', 'tax', 'advanced', E'Choosing the right business structure dramatically impacts your tax burden.\n\n## Structures & Tax\n- **Sole Proprietorship**: Income at personal rates (up to 30%)\n- **Partnership**: Profits shared and taxed at individual rates\n- **Limited Company**: Corporate tax 30%. Key advantage: retained profits taxed at corporate rate\n\n## VAT Registration\nRequired if turnover exceeds 100M TZS annually. Voluntary registration allows input VAT recovery.\n\n## Transfer Pricing & Optimization\n- Pay family reasonable salaries for real work\n- Deduct all legitimate business expenses\n- Time purchases for maximum depreciation\n- Consider EPZ/special economic zone incentives', 12, 37);

-- WEALTH: New category
INSERT INTO financial_lessons (title, category, difficulty, content, duration_minutes, order_index) VALUES
('The Wealth Building Formula', 'wealth', 'intermediate', E'Wealth = Income x Savings Rate x Time x Rate of Return. Master all four.\n\n## Variable 1: Income — Negotiate salary, add income streams, build premium skills\n## Variable 2: Savings Rate — Save 50% = independence in ~17 years. Save 10% = ~51 years.\n## Variable 3: Time — Starting at 25 vs 35 can mean millions in difference\n## Variable 4: Rate of Return — Moving from 5% to 10% roughly doubles final wealth\n\n## The Millionaire Math\nSaving 500,000 TZS/month at 12% return:\n- 10 years: ~115M TZS\n- 20 years: ~500M TZS\n- 30 years: ~1.75B TZS', 10, 40),

('Multiple Income Streams', 'wealth', 'intermediate', E'Wealthy people don''t rely on one income source.\n\n## The 7 Income Streams\n1. **Earned**: Salary (active)\n2. **Business**: Side business (semi-active)\n3. **Interest**: T-bills, deposits (passive)\n4. **Dividend**: Stock payouts (passive)\n5. **Rental**: Property (semi-passive)\n6. **Capital Gains**: Asset appreciation (variable)\n7. **Royalty**: Digital products, courses (passive)\n\n## Strategy: Build One at a Time\n1. Master earned income\n2. Save to invest → interest income\n3. Start side business\n4. Invest profits → dividends + capital gains\n5. Buy property → rental income\n6. Create digital assets → royalties\n\nAim for 3+ income streams within 5 years.', 10, 41),

('Financial Independence & FIRE', 'wealth', 'advanced', E'Financial Independence, Retire Early is achievable in East Africa.\n\n## The FIRE Number\nAnnual expenses x 25 = Your FIRE number\nMonthly expenses 2M TZS → FIRE number: 600M TZS\n\n## FIRE Variations\n- **LeanFIRE**: Minimal lifestyle, lower number\n- **FatFIRE**: Comfortable lifestyle, higher number\n- **CoastFIRE**: Save aggressively when young, let compounding work\n- **BaristaFIRE**: Partially independent, work part-time\n\n## East African Advantages\n- Lower cost of living = lower FIRE number\n- Government securities offer 8-12% risk-free\n- The 4% rule becomes 6-8% with local returns\n- Community support systems', 15, 42),

('Generational Wealth & Legacy Planning', 'wealth', 'advanced', E'True wealth is for your children and their children.\n\n## The Challenge\n70% of wealth lost by 2nd generation, 90% by 3rd. Reason: Financial literacy isn''t inherited.\n\n## Building Lasting Wealth\n1. **Educate family** about money from age 5+\n2. **Structure assets** in trusts, companies that survive you\n3. **Life insurance**: 10x annual income minimum\n4. **Write a will NOW** and update with life events\n5. **Business succession**: Document processes, train successors\n\n## Annual Family Wealth Meetings\n- Review financial goals\n- Discuss money values\n- Teach investment concepts\n- Plan for education and housing', 15, 43);

-- BUSINESS: More lessons  
INSERT INTO financial_lessons (title, category, difficulty, content, duration_minutes, order_index) VALUES
('Cash Flow Management for Entrepreneurs', 'business', 'intermediate', E'Cash flow is the #1 reason businesses fail.\n\n## Cash Flow vs Profit\nA business can be profitable on paper and still run out of cash!\n\n## Managing the Gap\n- Shorten receivables: Offer 2% discount for early payment\n- Lengthen payables: Negotiate 30-60 day terms\n- Reduce inventory: Just-in-time ordering\n- Invoice immediately\n\n## Cash Flow Forecasting\nProject monthly for 6 months ahead with conservative income estimates.\n\n## Emergency Measures\n- Maintain 3 months operating expenses in reserve\n- Have pre-approved line of credit\n- Know which expenses can be cut/delayed', 10, 50),

('Starting a Side Hustle That Scales', 'business', 'beginner', E'A side hustle is the fastest way to increase income.\n\n## High-Potential Side Hustles\n### Service-Based: Freelancing, social media management, tutoring, photography\n### Product-Based: E-commerce, food delivery, agricultural products\n### Digital (Scalable): Online courses, apps, digital marketing agency\n\n## The Side Hustle Formula\n1. Start with existing skills\n2. Find paying customers FIRST\n3. Keep your day job until side income = 2x expenses\n4. Reinvest 80% of profits\n5. Systematize and delegate\n\n## Financial Tracking\nSeparate business and personal from day one. Save 30% of business income for taxes.', 8, 51),

('Financial Statements Every Owner Must Know', 'business', 'advanced', E'Master these three documents to run a profitable business.\n\n## 1. Income Statement (P&L)\nRevenue - COGS = Gross Profit - Operating Expenses = Net Profit\nGross Margin below 30%: pricing or cost problem\n\n## 2. Balance Sheet\nAssets = Liabilities + Equity\nCurrent Ratio > 1.5 = healthy\n\n## 3. Cash Flow Statement\nOperating + Investing + Financing activities\n\n## Key Ratios\n- Current Ratio: Current Assets / Current Liabilities (>1.5)\n- Debt-to-Equity: Total Debt / Equity (<2)\n- Return on Equity: Net Profit / Equity (>15% = strong)', 12, 52);

-- SECURITY: Advanced
INSERT INTO financial_lessons (title, category, difficulty, content, duration_minutes, order_index) VALUES
('Digital Financial Security', 'security', 'intermediate', E'Protecting your money online is as important as earning it.\n\n## Mobile Money Security\n- Never share PIN or OTP with anyone\n- Register for SIM swap notifications\n- Verify ALL incoming money before acting\n\n## Investment Scam Red Flags\n- Guaranteed returns above market rates\n- Pressure to invest quickly\n- Unregistered with CMSA or BOT\n- Recruiting others = pyramid scheme\n\n## Recovery If Compromised\n1. Contact bank/provider IMMEDIATELY\n2. Change all passwords\n3. File police report\n4. Monitor accounts for 90 days', 8, 55),

('Advanced Financial Privacy', 'security', 'advanced', E'Financial privacy is financial security.\n\n## Minimizing Exposure\n- Use cash for sensitive purchases\n- Multiple accounts — don''t keep everything in one place\n- Review app permissions regularly\n- Don''t flaunt wealth on social media\n\n## Identity Theft Prevention\n- Guard TIN and ID numbers\n- Shred financial documents\n- Use unique email for financial accounts\n- Password manager for all accounts\n- Hardware security keys for critical accounts', 10, 56);

-- TRACKING: Advanced
INSERT INTO financial_lessons (title, category, difficulty, content, duration_minutes, order_index) VALUES
('Advanced Transaction Analysis', 'tracking', 'intermediate', E'Go beyond basic categorization to find powerful spending insights.\n\n## Pattern Recognition\n- Day of week spending patterns\n- Pre-payday vs post-payday behavior\n- Seasonal spending cycles\n- Late-night impulse purchases\n\n## Advanced Metrics\n- **Expense Velocity**: How quickly money leaves after payday\n- **Spending Concentration**: % in top 3 categories\n- **Discretionary Ratio**: Wants / Total (aim <30%)\n- **Recurring vs One-time**: Subscription lock-in\n\n## The 30-Day Challenge\nTrack EVERY expense, categorize ruthlessly, identify top 3 leaks, set reduction targets.', 8, 60),

('Net Worth Tracking & Milestones', 'tracking', 'intermediate', E'Your net worth is the single most important financial number.\n\n## Net Worth = Assets - Liabilities\nTrack: Cash, bank balances, investments, real estate, SACCO savings\nMinus: All loans, mortgages, credit balances, personal debts\n\n## Milestones to Celebrate\n1. Net Worth = 0 (debt-free!)\n2. 1 month expenses saved\n3. 3 months emergency fund\n4. Net worth = annual income\n5. Net worth = 5x income\n6. Net worth = 10x income\n7. Financial Independence\n\n## The Power of Tracking\nPeople who track net worth monthly accumulate 2-3x more wealth than those who don''t.', 8, 61)
